"""added to order worker field

Revision ID: 0fc231d608aa
Revises: 55c4bbc3a735
Create Date: 2026-01-09 17:04:18.022573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc231d608aa'
down_revision: Union[str, Sequence[str], None] = '55c4bbc3a735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'worker_id')
    # ### end Alembic commands ###
