"""change order response

Revision ID: 55c4bbc3a735
Revises: b7df3d757130
Create Date: 2026-01-07 14:09:30.546882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c4bbc3a735'
down_revision: Union[str, Sequence[str], None] = 'b7df3d757130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_responses', sa.Column('is_skipped', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_responses', 'is_skipped')
    # ### end Alembic commands ###
